# Generated by Django 4.1.1 on 2022-09-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='full_name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='notes',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
