# Generated by Django 4.1.1 on 2022-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_contactmessage_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='date_time',
            field=models.DateField(),
        ),
    ]
